### ISSUE TITLE
Site framework is required but not documented, Site framework should be optional

### ISSUE THREAD

**Issue by mentholi** [mvpdev/django-eav#23]
It seems that trying to use django-eav without Django's site framework in installed apps causes errors. This doesnt seem to be documented anywhere. Also it would be nice to have Sites framework integration as optional feature.

Run server with eav on installed apps and no Sites framework:
Validating models...

```
CommandError: One or more models did not validate:
eav.attribute: 'site' has a relation with model <class 'django.contrib.sites.models.Site'>, which has either not been installed or is abstract.
```

**Comment by genisd** [comment]
Just as a fyi, got the same issue over here.

**Comment by stillmatic** [comment]
This error shows up for me in this form.
```
ERRORS:
eav.Attribute.site: (fields.E300) Field defines a relation with model 'Site', which is either not installed, or is abstract.
```

**Comment by jpwhite3** [comment]
There is a pull request open for this
