### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'related_name'

### ISSUE THREAD

**Issue by hramezani** [mvpdev/django-eav#26]
when i want to register a model i got this error:

    TypeError: __init__() got an unexpected keyword argument 'related_name'

**Comment by madEng84** [comment]
Hi @hramezani,
You can see the fix in my branch.
https://github.com/mvpdev/django-eav/pull/27

**Comment by hramezani** [comment]
Hi @madEng84 ,
thanks.
