### ISSUE TITLE
Doesn't work with Django 1.9

### ISSUE THREAD

**Issue by frbry** [mvpdev/django-eav#35]
`django.contrib.contenttypes.generic` is deprecated and removed in Django 1.9 which causes django-eav to break as it is referenced from the module `eav.models`.

**Comment by marcoooo** [comment]
Hi, I forked the repo minutes ago and push changes for compatibility. I don't know yet if this correction should be pulled back to main repo.
The push is here : https://github.com/Archi-Logic/django-eav/commit/91d3c470427ea67763a1909856a82aab0be8a4a6

Have a nice day.
Marc

**Comment by MrSaints** [comment]
I believe this can be closed now.
