### ISSUE TITLE
eav.register need sites app

### ISSUE THREAD

**Issue by lhy1149** [mvpdev/django-eav#39]
hi,
eav.register(MonitorObject) trigger：

RuntimeError: Model class django.contrib.sites.models.Site doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

put django.contrib.sites into INSTALLED_APPS resolve this

this maybe need documented

**Comment by MagnetonBora** [comment]
Have the same problem.

In my case, after I had added eav to INSTALLED_APPS section I got `django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet` error raised.
