### ISSUE TITLE
validate_enum

### ISSUE THREAD

**Issue by ouhouhsami** [mvpdev/django-eav#4]
It seems to me that there is a problem w/ validation process for validate_enum(value) method.
first, the synthax from .models import EnumValue is no longer right
next, it seems that 'if not isinstance(value, EnumValue):' is always true even if it's false. value.**class** is unicode for me each time.

**Comment by madEng84** [comment]
Don't you want to resolve this issue? @dgelvin 
What about a merge with @reinoudvansanten 's fork?

**Comment by Sahloul** [comment]
Closed by #20
