### ISSUE TITLE
Repo still alive? 

### ISSUE THREAD

**Issue by vincentwhales** [mvpdev/django-eav#51]
Hey guys, just want to touch base on whether this repo is still being actively maintained. 

There are a few great PRs out there that requires merging for the latest Django 2.0.X

**Comment by Sahloul** [comment]
@vincentwhales Thank you for your concern. The intention is to keep it alive, but seems we got busy with other staff.
We would appreciate your help in reviewing the current PRs and point out flows, in order to speed up the process.
